# Generated by Django 4.2.3 on 2023-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
